### ISSUE TITLE
identify mappers with limited experience

### ISSUE THREAD

**Issue by althio** [osmlab/osm-meta-util#11]
Hi metadata wizards,

from the HOT mailing list this is a request from the Nepal Activation coordinators

> Is there a overpass skilled person to write the script that can identify mappers with limited experience (recent mapper ID or number of contributions less than let us say 5,000) over Nepal, so that we can check their contributions and give advice about how to improve them. 

Would that be possible (easy???) with your tool?
Could you provide detailed instructions for low-tech users?

All the best!

Ben - althio

cc: @severinmenard

**Comment by severinmenard** [comment]
Hi Althio,

Someone answered in the thread that Pascal did this great table:
http://resultmaps.neis-one.org/newestosmcountry.php?c=Nepal

I contacted him to know if he could a thrid table in the page to show only
the ones who mapped more than 1 day, with their total of edits

**Comment by mikelmaron** [comment]
out of scope for osm-meta-util
